#!/usr/bin/env sh
# Rebuilds the generated files of map/: objects/_index.md from every card's frontmatter,
# and the twins AGENTS.md + routing.md from CLAUDE.md. `--check` exits 1 when any is stale.
set -eu
cd "$(dirname "$0")/.."

index() {
  printf '# Objects index\n\nGenerated by `_meta/build.sh` from card frontmatter. Never hand-edit.\n\n'
  printf '| Card | Universe | Status | Entity |\n|---|---|---|---|\n'
  find objects -mindepth 2 -name '*.md' | LC_ALL=C sort | while read -r f; do
    n=${f#objects/}; n=${n%.md}
    u=$(sed -n 's/^universe: *//p' "$f" | head -1)
    s=$(sed -n 's/^status: *//p' "$f" | head -1)
    e=$(sed -n 's/^entity: *//p' "$f" | head -1)
    printf '| [[%s]] | %s | %s | `%s` |\n' "$n" "$u" "$s" "$e"
  done
}

if [ "${1:-}" = "--check" ]; then
  index | diff -q - objects/_index.md >/dev/null || { echo "map: objects/_index.md is stale, run map/_meta/build.sh"; exit 1; }
  for t in AGENTS.md routing.md; do
    cmp -s CLAUDE.md "$t" || { echo "map: $t differs from CLAUDE.md, run map/_meta/build.sh"; exit 1; }
  done
  echo "map: generated files fresh"
  exit 0
fi

index > objects/_index.md
cp CLAUDE.md AGENTS.md
cp CLAUDE.md routing.md
echo "map: rebuilt objects/_index.md, AGENTS.md, routing.md"
