import type { Need, RouteApps } from "./access.js";

/**
 * ConsolePortal's handlers (`console.ts`) and what each needs. With no `client` the need is
 * checked at Wren's own apps. Installs need `manage`, which only an admin holds on the team
 * (pricing is William's). Type imports only, so the edge Worker bundles it alone.
 */
export const CONSOLE_ROUTES = {
  view: "wren:read",
  loops: "wren:read",
  setLoop: "wren:run",
  // The team's records at Wren; a client's catalog (console.component) at that client.
  recordsTypes: "read",
  recordsList: "read",
  recordsGet: "read",
  recordsExport: "read",
  recordsStats: "read",
  // A record's edits (`edits.ts`): the handler checks `run` at Wren, or `act` on that row.
  recordsEdit: "wren:act",
  recordsUndo: "wren:act",
  recordsAsk: "wren:act",
  // A viewer's own saved views and prefs, where they look; sharing a view checks `manage`.
  savedViews: "read",
  saveView: "read",
  removeView: "read",
  moveViews: "read",
  prefs: "read",
  setPref: "read",
  // Access (`access-console.ts`): roles, grants, issues and asks where the viewer looks; each
  // handler checks what it names (manage, comment, act, or who could grant it).
  issues: "read",
  roleSave: "read",
  roleCopy: "read",
  roleGrant: "read",
  roleRemove: "read",
  grantAdd: "read",
  grantEnd: "read",
  issueRaise: "read",
  issueResolve: "read",
  accessAsk: "read",
  askDecide: "read",
  // Custom fields and business facts where the viewer looks; changes check `manage` there.
  customFields: "read",
  customFieldSave: "read",
  customFieldOrder: "read",
  businessFacts: "read",
  businessFactSave: "read",
  // The Library's snippets: the team reads them anywhere it drafts, changes them at Wren.
  snippets: "read",
  snippetAdd: "wren:run",
  snippetRemove: "wren:run",
  // Flags: the team at Wren, a release decision (the handler checks `manage`).
  flagAdd: "wren:run",
  flagRemove: "wren:run",
  // Experiments: Start and Ship put a variant live on the site (the handler checks `manage`).
  experimentAdd: "wren:run",
  experimentStart: "wren:run",
  experimentShip: "wren:run",
  experimentStop: "wren:run",
  experimentRemove: "wren:run",
  // Surveys: a live site survey is on the public site (the handler checks `manage`).
  surveyAdd: "wren:run",
  surveyStart: "wren:run",
  surveyPause: "wren:run",
  surveyRemove: "wren:run",
  // A client login's own portal surveys: what it's due, and its answer.
  surveysDue: "read",
  surveyAnswer: "read",
  // A login's own access tokens for AI tools (designs/2026-10-09-mcp.md): its email only.
  tokens: "read",
  tokenMake: "read",
  tokenRevoke: "read",
  addClient: "wren:manage",
  // Any handler needs `run` over all of Wren, or `act` on the row its record type declares the
  // call for (`callOn`). A handler with an effect needs `effect` too.
  call: "wren:act",
  setLook: "manage",
  install: "manage",
  configure: "manage",
  uninstall: "manage",
  ask: "manage",
  // A client's account from the Shop: the team's (the handler checks), audited.
  connect: "manage",
  // Templates on a client: the team's, like installs. Approving one makes it send or spend: an
  // admin at Wren (the handler checks `effect` and `money` too).
  templatePlan: "manage",
  templateInstall: "manage",
  templatePublish: "manage",
  templateUninstall: "manage",
  templateApprove: "wren:manage",
  templateDecline: "wren:manage",
  templateInstalls: "read",
  // A workflow's wiring, saved for Wren or a client from the canvas: the team's. A draft runs
  // nowhere; Publish of one that sends or spends also checks `effect` and `money` inside.
  workflowSave: "wren:manage",
  workflowPublish: "wren:manage",
  workflowDiscard: "wren:manage",
  // A live workflow kept as a template: it starts nothing; installing it is the Shop's path.
  workflowTemplateSave: "wren:manage",
  // A saved template off the Marketplace: refused while a client runs it live.
  workflowTemplateDelete: "wren:manage",
  workflowAsk: "wren:manage",
  workflowAnswer: "wren:manage",
  // A made workflow: built from a prompt or blank, listed, deleted while not live.
  workflowBuild: "wren:manage",
  workflowsMade: "wren:read",
  workflowDelete: "wren:manage",
  // A dry test of a draft: nothing is claimed or sent, so running things is enough.
  workflowTest: "wren:run",
  // A workflow's doors: the team reads them masked; seeing a whole token or a new one is `manage`.
  workflowDoors: "wren:read",
  doorReveal: "wren:manage",
  doorRotate: "wren:manage",
  // A failed spine step, run again: it may send, so it needs what an effect does.
  retryEvent: "wren:effect",
  replay: "wren:effect",
  // A held unit runs again, a paused source resumes.
  releaseHold: "wren:run",
  // Ask: a question to Claude Code on William's Mac, read only (`ask.ts`).
  question: "wren:run",
  // The Team page: an admin's.
  teamSet: "wren:team",
  teamRemove: "wren:team",
} as const satisfies Record<string, Need>;
/** Where each route works (`RouteAt`); null where the handler checks the record type. */
export const CONSOLE_APPS = {
  // Records, saved views, prefs and calls: the handler checks each record type.
  "*": null,
  view: "outbound",
  loops: "loops",
  setLoop: "loops",
  flagAdd: "loops",
  flagRemove: "loops",
  experimentAdd: "marketing",
  experimentStart: "marketing",
  experimentShip: "marketing",
  experimentStop: "marketing",
  experimentRemove: "marketing",
  surveyAdd: "marketing",
  surveyStart: "marketing",
  surveyPause: "marketing",
  surveyRemove: "marketing",
  snippetAdd: "library",
  snippetRemove: "library",
  addClient: "clients",
  setLook: "account",
  install: "marketplace",
  configure: "marketplace",
  uninstall: "marketplace",
  ask: "marketplace",
  connect: "marketplace",
  templatePlan: "marketplace",
  templateInstall: "marketplace",
  templatePublish: "marketplace",
  templateUninstall: "marketplace",
  templateApprove: "workflows",
  templateDecline: "workflows",
  templateInstalls: "marketplace",
  workflowSave: "workflows",
  workflowPublish: "workflows",
  workflowDiscard: "workflows",
  workflowTemplateSave: "workflows",
  workflowTemplateDelete: "workflows",
  workflowAsk: "workflows",
  workflowAnswer: "workflows",
  workflowBuild: "workflows",
  workflowsMade: "workflows",
  workflowDelete: "workflows",
  workflowTest: "workflows",
  workflowDoors: "workflows",
  doorReveal: "workflows",
  doorRotate: "workflows",
  retryEvent: "workflows",
  replay: "workflows",
  releaseHold: "workflows",
  question: "ask",
  teamSet: "team",
  teamRemove: "team",
} as const satisfies RouteApps<typeof CONSOLE_ROUTES>;
export type ConsoleRoute = keyof typeof CONSOLE_ROUTES;
/** The ones that change something: never cached, never on the demo. */
export const CONSOLE_WRITES: readonly ConsoleRoute[] = [
  "customFieldSave",
  "customFieldOrder",
  "businessFactSave",
  "roleSave",
  "roleCopy",
  "roleGrant",
  "roleRemove",
  "grantAdd",
  "grantEnd",
  "issueRaise",
  "issueResolve",
  "accessAsk",
  "askDecide",
  "setLoop",
  "recordsEdit",
  "recordsUndo",
  "recordsAsk",
  "saveView",
  "removeView",
  "moveViews",
  "setPref",
  "snippetAdd",
  "snippetRemove",
  "flagAdd",
  "flagRemove",
  "experimentAdd",
  "experimentStart",
  "experimentShip",
  "experimentStop",
  "experimentRemove",
  "surveyAdd",
  "surveyStart",
  "surveyPause",
  "surveyRemove",
  "surveyAnswer",
  "tokenMake",
  "tokenRevoke",
  "addClient",
  "call",
  "setLook",
  "install",
  "configure",
  "uninstall",
  "ask",
  "connect",
  "templateInstall",
  "templatePublish",
  "templateUninstall",
  "templateApprove",
  "templateDecline",
  "workflowSave",
  "workflowPublish",
  "workflowDiscard",
  "workflowTemplateSave",
  "workflowTemplateDelete",
  "workflowAsk",
  "workflowBuild",
  "workflowDelete",
  "doorReveal",
  "doorRotate",
  "retryEvent",
  "replay",
  "releaseHold",
  "question",
  "teamSet",
  "teamRemove",
];
