CREATE TABLE "video_edits" (
	"id" serial NOT NULL,
	"title" text DEFAULT '' NOT NULL,
	"state" varchar(16) DEFAULT 'added' NOT NULL,
	"dir" text NOT NULL,
	"tracks" jsonb NOT NULL,
	"script" jsonb,
	"words" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"cuts" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"layout" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"captions" jsonb DEFAULT '{"on":true,"style":"word"}'::jsonb NOT NULL,
	"shorts" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"chapters" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"thumbnail" jsonb,
	"looks" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"files" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"keys" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "pk_video_edits" PRIMARY KEY("id"),
	CONSTRAINT "ck_video_edits_state" CHECK (("state")::text = ANY ((ARRAY['added'::character varying, 'edited'::character varying, 'rendered'::character varying, 'approved'::character varying, 'uploaded'::character varying])::text[]))
);
